
#define LED_PIN 25 
#define TEST_LED_PIN 17
#define RELOAD_BUTTON_PIN 18
#define TRIGGER_PIN 16

// Ammo Counter
#define AMMO_BAR_PIN_1  6
#define AMMO_BAR_PIN_2  7
#define AMMO_BAR_PIN_3  8
#define AMMO_BAR_PIN_4  9
#define AMMO_BAR_PIN_5  10
#define AMMO_BAR_PIN_6  11
#define AMMO_BAR_PIN_7  12
#define AMMO_BAR_PIN_8  13
#define AMMO_BAR_PIN_9  14
#define AMMO_BAR_PIN_10 15

//#define AMMO_BAR_COUNT 10
// Helper list of ammo bar pins to allow itteration
#define AMMO_BAR_PIN_LIST (int[]){AMMO_BAR_PIN_1, AMMO_BAR_PIN_2, AMMO_BAR_PIN_3, AMMO_BAR_PIN_4, AMMO_BAR_PIN_5, AMMO_BAR_PIN_6, AMMO_BAR_PIN_7, AMMO_BAR_PIN_8, AMMO_BAR_PIN_9, AMMO_BAR_PIN_10}
#define _AMMO_BAR_PIN_LIST (int[]){AMMO_BAR_PIN_10, AMMO_BAR_PIN_9, AMMO_BAR_PIN_8, AMMO_BAR_PIN_7, AMMO_BAR_PIN_6, AMMO_BAR_PIN_5, AMMO_BAR_PIN_4, AMMO_BAR_PIN_3, AMMO_BAR_PIN_2, AMMO_BAR_PIN_1}
#define AMMO_BAR_COUNT sizeof(AMMO_BAR_PIN_LIST) / sizeof(AMMO_BAR_PIN_LIST[0])

// Laser
#define LASER_RED_PIN 19
#define LASER_BLUE_PIN 20
#define LASER_GREEN_PIN 21
#define LASER_PIN_LIST (int[]){LASER_RED_PIN, LASER_BLUE_PIN, LASER_GREEN_PIN}
#define LASER_PIN_COUNT sizeof(LASER_PIN_LIST) / sizeof(LASER_PIN_LIST[0])

// Laser colour indicator
#define LASER_IND_RED_PIN 3
#define LASER_IND_BLUE_PIN 4
#define LASER_IND_GREEN_PIN 5
#define LASER_IND_PIN_LIST (int[]){LASER_IND_RED_PIN, LASER_IND_BLUE_PIN, LASER_IND_GREEN_PIN}
#define LASER_IND_PIN_COUNT sizeof(LASER_IND_PIN_LIST) / sizeof(LASER_IND_PIN_LIST[0])

#define SOUND_PIN  2

